### PR TITLE
Decrease maximum cycle try counts and increase cycle multiplies for n…

### PR DESCRIPTION
**Pull request by justulka**
…ext try date time

### CODE REVIEW

**Review by MallyDev — APPROVED** [review]

**Comment by biskyt** [comment]
@apigram @preet90 - could one of you please review, assign the correct branch and merge if you're happy? It may need to go into the develop, a release/v4.1 or a bugfix/4.0.2 branch, depending on which OE version it is targeting.

@justulka - could you please advise on what release this change/fix is targeting, and what the Jira ticket number is? Nothing should be directly merged into master.

**Comment by justulka** [comment]
@biskyt This fix and potentially some other fixes apply to multiple versions and not necessarily goes together with OE versions.

I have created bugfix/v3.6.3 branch for this and can merge fixes there , but OE with 3.5 or even lower could run this branch.

I'll create the tickets for the fixes , but the not sure what to type in the fix versions

**Comment by justulka** [comment]
Recreated in https://github.com/openeyes/PayloadProcessor/pull/68

**Comment by biskyt** [comment]
@justulka - it will need merging up to the `bugfix/4.0.2`, `release/4.1` and `develop` branches too, to keep them in-sync.
Mark the fix version as 3.6.3 and 4.0.2 (there will never actually be a 3.6.3 release, as v3 is now deprecated)

Thanks

**Pull request merged**
