### PR TITLE
Fix/duplicate merging events on study uid

### PR DESCRIPTION
**Pull request by justulka**

### CODE REVIEW

**Comment by justulka** [comment]
Same STUDY UID causing merging of events when the STUDY UID is same from 2 different machines , very rare case , but it happened in GSTT LIVE

**Comment by justulka** [comment]
It shouldn't happen at all ,but not changing other device behavior and it the setting defaults to false

**Comment by justulka** [comment]
Currently this version is running on GSTT near live to test

**Review by preet90 — APPROVED** [review]

**Comment by justulka** [comment]
https://openeyes.atlassian.net/browse/OE-10699

**Pull request closed without merging**
