### PR TITLE
OE-10587 Payload processor docker container crashing when processing the dicom files that needs Tesseract

### PR DESCRIPTION
**Pull request by preet90**
Replaced the traineddata file with the one from the tesseract repo. 
Git is showing no file changed but I've tested the problematic dicom file after building the docker image on this branch and it worked fine.

### CODE REVIEW

**Review by justulka — APPROVED** [review]

**Comment by justulka** [comment]
The traineddata is from the tesseract website, but you might have github issues downloading larger files?

**Comment by preet90** [comment]
> The traineddata is from the tesseract website, but you might have github issues downloading larger files?

Do you mean the payload processor download files from github?

**Comment by justulka** [comment]
I had issues with getting the trained data with the git commands and i had to manaully download it from the github website and put it in the folder as i think you have to do something more to get big files across github , but not sure.

**Comment by justulka** [comment]
Can you try doing the same thing on master and see if it does it?

**Comment by preet90** [comment]
> I had issues with getting the trained data with the git commands and i had to manaully download it from the github website and put it in the folder as i think you have to do something more to get big files across github , but not sure.

You can use this command to download the complete file from github - 
`curl -LJO https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata`

**Comment by preet90** [comment]
@justulka I have updated the dockerfile to get the training data from the tesseract github repo rather than using the one that is in the payload processor repo. Left the training data in the resources folder there for now but it can be removed in the future.

**Comment by preet90** [comment]
@justulka Could you please review it and if everything is okay merge it. Thanks.

**Review by nathanieloon — APPROVED** [review]

**Review by justulka — APPROVED** [review]

**Comment by preet90** [comment]
@justulka could you please merge this. Thanks.

**Comment by justulka** [comment]
@preet90  done

**Pull request merged**
